language: python
python:
    - 2.7
before_install:

    # We do this to make sure we get dependencies
    - sudo apt-get update -qq
install: python setup.py install
#notifications:
#  email: false
#script: cd tests && sh TEST.sh
