__name__            = 'WSTSFU'
__version__         = '0.1.1'
__description__     = 'WorkSheet To Something Fucking Useful'
__author__          = 'Mitchell Stanton-Cook'
__author_email__    = 'm.stantoncook@gmail.com'
__url__             = 'http://github.com/mscook/WSTSFU'
__licence__         = 'ECL 2.0'
